#!/bin/bash



cd $OPENSHIFT_DATA_DIR

if [ -d "luvit" ] && [ "`cat luvit/VERSION`" == $LUVIT_VERSION ]; then

  echo "Luvit already installed"

else

  echo "Installing latest Luvit"

  if [ -d "luvit" ]; then
    rm -rf luvit
  fi

  curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh

fi

PATH="${OPENSHIFT_DATA_DIR}:$PATH"

cd $OPENSHIFT_REPO_DIR

CMD="luvit main.lua"

nohup $CMD > $OPENSHIFT_LOG_DIR/luvit.log 2>&1 &

echo $! > ${OPENSHIFT_LOG_DIR}luvit.pid
